export const DISPUTE_STATUSES = {
  OPEN: 'OPEN',
  EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED_BUYER: 'RESOLVED_BUYER',
  RESOLVED_PROVIDER: 'RESOLVED_PROVIDER',
  ESCALATED: 'ESCALATED',
} as const;

export type DisputeStatus =
  (typeof DISPUTE_STATUSES)[keyof typeof DISPUTE_STATUSES];

export const DISPUTE_RESOLUTIONS = {
  BUYER_FAVOR: 'BUYER_FAVOR',
  PROVIDER_FAVOR: 'PROVIDER_FAVOR',
  ESCALATED: 'ESCALATED',
} as const;

export type DisputeResolution =
  (typeof DISPUTE_RESOLUTIONS)[keyof typeof DISPUTE_RESOLUTIONS];
