export enum ConnectorType {
  REST_API = 'REST_API',
  POSTGRESQL = 'POSTGRESQL',
  CSV = 'CSV',
  WEBHOOK = 'WEBHOOK',
}

export enum SyncStatus {
  IDLE = 'IDLE',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum SyncSchedule {
  MANUAL = 'MANUAL',
  EVERY_15_MIN = 'EVERY_15_MIN',
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
}

export enum DashboardStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum WidgetType {
  LINE = 'LINE',
  BAR = 'BAR',
  PIE_DONUT = 'PIE_DONUT',
  AREA = 'AREA',
  KPI_CARD = 'KPI_CARD',
  TABLE = 'TABLE',
  FUNNEL = 'FUNNEL',
}

export enum AggregationFunction {
  SUM = 'SUM',
  AVG = 'AVG',
  COUNT = 'COUNT',
  MIN = 'MIN',
  MAX = 'MAX',
}

export enum FieldType {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  DATE = 'DATE',
  BOOLEAN = 'BOOLEAN',
}

export enum FieldRole {
  DIMENSION = 'DIMENSION',
  METRIC = 'METRIC',
}

export enum SubscriptionTier {
  FREE = 'FREE',
  PRO = 'PRO',
  ENTERPRISE = 'ENTERPRISE',
}

export enum AuditAction {
  TENANT_CREATED = 'TENANT_CREATED',
  TENANT_UPDATED = 'TENANT_UPDATED',
  TENANT_DELETED = 'TENANT_DELETED',
  DATASOURCE_CREATED = 'DATASOURCE_CREATED',
  DATASOURCE_UPDATED = 'DATASOURCE_UPDATED',
  DATASOURCE_DELETED = 'DATASOURCE_DELETED',
  DATASOURCE_TEST_CONNECTION = 'DATASOURCE_TEST_CONNECTION',
  DASHBOARD_CREATED = 'DASHBOARD_CREATED',
  DASHBOARD_UPDATED = 'DASHBOARD_UPDATED',
  DASHBOARD_PUBLISHED = 'DASHBOARD_PUBLISHED',
  DASHBOARD_ARCHIVED = 'DASHBOARD_ARCHIVED',
  DASHBOARD_REVERTED_TO_DRAFT = 'DASHBOARD_REVERTED_TO_DRAFT',
  DASHBOARD_DELETED = 'DASHBOARD_DELETED',
  WIDGET_CREATED = 'WIDGET_CREATED',
  WIDGET_UPDATED = 'WIDGET_UPDATED',
  WIDGET_DELETED = 'WIDGET_DELETED',
  SYNC_STARTED = 'SYNC_STARTED',
  SYNC_COMPLETED = 'SYNC_COMPLETED',
  SYNC_FAILED = 'SYNC_FAILED',
  SYNC_PAUSED = 'SYNC_PAUSED',
  SYNC_RESUMED = 'SYNC_RESUMED',
  EMBED_CONFIG_UPDATED = 'EMBED_CONFIG_UPDATED',
  API_KEY_CREATED = 'API_KEY_CREATED',
  API_KEY_REVOKED = 'API_KEY_REVOKED',
  THEME_UPDATED = 'THEME_UPDATED',
  TIER_UPGRADED = 'TIER_UPGRADED',
  TIER_DOWNGRADED = 'TIER_DOWNGRADED',
  DATA_EXPORTED = 'DATA_EXPORTED',
  ACCOUNT_DELETION_REQUESTED = 'ACCOUNT_DELETION_REQUESTED',
}

export enum GroupingPeriod {
  NONE = 'NONE',
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}

export enum DateRangePreset {
  LAST_7_DAYS = 'LAST_7_DAYS',
  LAST_30_DAYS = 'LAST_30_DAYS',
  LAST_90_DAYS = 'LAST_90_DAYS',
  CUSTOM = 'CUSTOM',
  ALL_TIME = 'ALL_TIME',
}

export enum ApiKeyType {
  ADMIN = 'ADMIN',
  EMBED = 'EMBED',
}
