/**
 * Shared enums mirroring Prisma schema.
 * Keep in sync with apps/api/prisma/schema.prisma.
 */

export enum UserRole {
  BUYER = 'BUYER',
  PROVIDER = 'PROVIDER',
  ADMIN = 'ADMIN',
}

export enum TransactionStatus {
  CREATED = 'CREATED',
  PAYMENT_HELD = 'PAYMENT_HELD',
  DELIVERED = 'DELIVERED',
  RELEASED = 'RELEASED',
  PAID_OUT = 'PAID_OUT',
  DISPUTED = 'DISPUTED',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED_RELEASED = 'RESOLVED_RELEASED',
  RESOLVED_REFUNDED = 'RESOLVED_REFUNDED',
  ESCALATED = 'ESCALATED',
  CLOSED = 'CLOSED',
}

export enum DisputeReason {
  NOT_DELIVERED = 'NOT_DELIVERED',
  NOT_AS_DESCRIBED = 'NOT_AS_DESCRIBED',
  QUALITY_ISSUE = 'QUALITY_ISSUE',
  LATE_DELIVERY = 'LATE_DELIVERY',
  COMMUNICATION_ISSUE = 'COMMUNICATION_ISSUE',
  OTHER = 'OTHER',
}

export enum PayoutStatus {
  PENDING = 'PENDING',
  IN_TRANSIT = 'IN_TRANSIT',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum OnboardingStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING = 'PENDING',
  COMPLETE = 'COMPLETE',
  RESTRICTED = 'RESTRICTED',
}

export enum WebhookStatus {
  RECEIVED = 'RECEIVED',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}

export enum AuditAction {
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  PAYMENT_HELD = 'PAYMENT_HELD',
  DELIVERY_MARKED = 'DELIVERY_MARKED',
  DELIVERY_CONFIRMED = 'DELIVERY_CONFIRMED',
  FUNDS_RELEASED = 'FUNDS_RELEASED',
  FUNDS_REFUNDED = 'FUNDS_REFUNDED',
  PAYOUT_INITIATED = 'PAYOUT_INITIATED',
  PAYOUT_COMPLETED = 'PAYOUT_COMPLETED',
  PAYOUT_FAILED = 'PAYOUT_FAILED',
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  DISPUTE_EVIDENCE_ADDED = 'DISPUTE_EVIDENCE_ADDED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  DISPUTE_ESCALATED = 'DISPUTE_ESCALATED',
  HOLD_EXPIRED = 'HOLD_EXPIRED',
  TRANSACTION_CANCELLED = 'TRANSACTION_CANCELLED',
  AUTO_RELEASE_TRIGGERED = 'AUTO_RELEASE_TRIGGERED',
  PROVIDER_ONBOARDED = 'PROVIDER_ONBOARDED',
  PROVIDER_RESTRICTED = 'PROVIDER_RESTRICTED',
}
